// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnLHIq4A01LTx1JrZ_jyRhVJttcQDXe8Y',
    appId: '1:597617290022:web:b1b0bb1f759156baa1afe7',
    messagingSenderId: '597617290022',
    projectId: 'bdevm3u',
    authDomain: 'bdevm3u.firebaseapp.com',
    storageBucket: 'bdevm3u.firebasestorage.app',
    measurementId: 'G-KX3PYQBB76',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmqrxEhr_sMDxkUnSMOl8Raf54t6g9Ow0',
    appId: '1:597617290022:android:c126d7214fffcfd7a1afe7',
    messagingSenderId: '597617290022',
    projectId: 'bdevm3u',
    storageBucket: 'bdevm3u.firebasestorage.app',
  );
}
